version: "3.8"

services:
  redis:
    image: redis:6.0-alpine
    restart: always

  ingest:
    image: subsquid/substrate-ingest:firesquid
    restart: on-failure
    command: [
      "-e", "wss://kusama-rpc.polkadot.io",
      "-e", "wss://kusama-rpc.dwellir.com",
      "--out", "postgres://postgress:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=archive&ssl=true"
    ]
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: "0"  # Добавляем отключение проверки SSL-сертификатов

  gateway:
    image: subsquid/substrate-gateway:firesquid
    environment:
      DATABASE_MAX_CONNECTIONS: 5
      RUST_LOG: "actix_web=info,actix_server=info"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"  # Добавляем отключение проверки SSL-сертификатов
    command: [
      "--database-url", "postgres://postgress:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=archive&ssl=true"
    ]
    ports:
      - "8888:8000"

  explorer:
    image: subsquid/substrate-explorer:firesquid
    environment:
      DB_TYPE: postgres
      DB_HOST: ${DB_HOST}
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_SCHEMA: "archive"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"  # Добавляем отключение проверки SSL-сертификатов
    ports:
      - "4444:3000"

  indexer:
    image: subsquid/hydra-indexer:4
    restart: unless-stopped
    environment:
      INDEXER_WORKERS: 5
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      REDIS_URI: ${REDIS_URI}
      BLOCK_HEIGHT: 0
      WS_PROVIDER_ENDPOINT_URI: wss://kusama-rpc.polkadot.io
      DB_SCHEMA: "indexer"
      NODE_TLS_REJECT_UNAUTHORIZED: "0"  # Добавляем отключение проверки SSL-сертификатов
    command: >
      sh -c "yarn db:bootstrap && yarn start:prod"

  indexer-gateway:
    image: subsquid/hydra-indexer-gateway:4
    restart: unless-stopped
    environment:
      DEV_MODE: true
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: "indexer"
      HYDRA_INDEXER_STATUS_SERVICE: http://indexer-status-service:8081/status
      NODE_TLS_REJECT_UNAUTHORIZED: "0"  # Добавляем отключение проверки SSL-сертификатов
    ports:
      - "8080:8080"

  indexer-status-service:
    image: subsquid/hydra-indexer-status-service:4
    restart: unless-stopped
    environment:
      REDIS_URI: ${REDIS_URI}
      PORT: 8081
      NODE_TLS_REJECT_UNAUTHORIZED: "0"  # Добавляем отключение проверки SSL-сертификатов
