version: "3.4"

services:
  redis:
    image: redis:6.0-alpine
    restart: always
    volumes:
      - redis-data:/data

  indexer:
    image: subsquid/hydra-indexer:4
    restart: unless-stopped
    environment:
      INDEXER_WORKERS: 5
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      REDIS_URI: ${REDIS_URI}
      BLOCK_HEIGHT: 0
      WS_PROVIDER_ENDPOINT_URI: wss://kusama-rpc.polkadot.ioo
      DB_SCHEMA: "indexer"
    command: >
      sh -c "yarn --cwd /app/indexer db:bootstrap && yarn --cwd /app/indexer start:prod"
    volumes:
      - ../:/app

  indexer-gateway:
    image: subsquid/hydra-indexer-gateway:4
    restart: unless-stopped
    depends_on:
      - indexer
    ports:
      - "8080:8080"
    environment:
      DEV_MODE: true
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      DB_SCHEMA: "indexer"
      HYDRA_INDEXER_STATUS_SERVICE: http://indexer-status-service:8081/status

  indexer-status-service:
    image: subsquid/hydra-indexer-status-service:4
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_URI: ${REDIS_URI}
      PORT: 8081

volumes:
  redis-data:
    driver: local
