version: "3.4"

services:
  redis:
    image: redis:6.0-alpine
    restart: always
    volumes:
      - redis-data:/data

  indexer:
    image: subsquid/hydra-indexer:4
    restart: unless-stopped
    environment:
      INDEXER_WORKERS: 5
      DB_NAME: postgress_4sgg
      DB_HOST: dpg-ct6bvabv2p9s739aq600-a.oregon-postgres.render.com
      DB_USER: postgress
      DB_PASS: YzHGemWnJKdIN53Lnxv6aPsW63TriqrG
      DB_PORT: 5432
      REDIS_URI: redis://redis:6379/0
      BLOCK_HEIGHT: 0
      WS_PROVIDER_ENDPOINT_URI: wss://kusama-rpc.polkadot.io
      DB_SCHEMA: "indexer"
    command: >
      sh -c "yarn --cwd /app/indexer db:bootstrap && yarn --cwd /app/indexer start:prod"
    volumes:
      - ../:/app

  indexer-gateway:
    image: subsquid/hydra-indexer-gateway:4
    restart: unless-stopped
    depends_on:
      - indexer
    ports:
      - "8080:8080"
    environment:
      DEV_MODE: true
      DB_NAME: postgress_4sgg
      DB_HOST: dpg-ct6bvabv2p9s739aq600-a.oregon-postgres.render.com
      DB_USER: postgress
      DB_PASS: YzHGemWnJKdIN53Lnxv6aPsW63TriqrG
      DB_PORT: 5432
      DB_SCHEMA: "indexer"
      HYDRA_INDEXER_STATUS_SERVICE: http://indexer-status-service:8081/status

  indexer-status-service:
    image: subsquid/hydra-indexer-status-service:4
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_URI: redis://redis:6379/0
      PORT: 8081

volumes:
  redis-data:
    driver: local
