version: "3.4"

services:
  db:
    image: postgres:12
    restart: always
    volumes:
      - ../data/indexer-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: indexer

  redis:
    image: redis:6.0-alpine
    restart: always
    volumes:
      - redis-data:/data

  indexer:
    image: subsquid/hydra-indexer:4
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - INDEXER_WORKERS=5
      - DB_NAME=indexer
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - REDIS_URI=redis://redis:6379/0
      - BLOCK_HEIGHT=0
      - WS_PROVIDER_ENDPOINT_URI=wss://kusama-asset-hub-rpc.polkadot.io
    command: >
      sh -c "yarn --cwd /app/indexer db:bootstrap && yarn --cwd /app/indexer start:prod"
    volumes:
      - ../:/app

  indexer-gateway:
    image: subsquid/hydra-indexer-gateway:4
    restart: unless-stopped
    depends_on:
      - indexer
    ports:
      - "8080:8080"
    environment:
      - DEV_MODE=true
      - DB_NAME=indexer
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - HYDRA_INDEXER_STATUS_SERVICE=http://indexer-status-service:8081/status

  indexer-status-service:
    image: subsquid/hydra-indexer-status-service:4
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_URI=redis://redis:6379/0
      - PORT=8081

volumes:
  redis-data:
    driver: local
