version: "3.4"

services:
  ingest:
    image: subsquid/substrate-ingest:firesquid
    restart: on-failure
    command: >
      ["-e", "wss://kusama-rpc.polkadot.io",
       "--out", "postgres://postgress:YzHGemWnJKdIN53Lnxv6aPsW63TriqrG@dpg-ct6bvabv2p9s739aq600-a.oregon-postgres.render.com:5432/postgress_4sgg?schema=archive&ssl=true"]
    volumes:
      - ../:/app

  gateway:
    image: subsquid/substrate-gateway:firesquid
    restart: on-failure
    environment:
      DATABASE_MAX_CONNECTIONS: 5
      RUST_LOG: "actix_web=info,actix_server=info"
    command: >
      ["--database-url", "postgres://postgress:YzHGemWnJKdIN53Lnxv6aPsW63TriqrG@dpg-ct6bvabv2p9s739aq600-a.oregon-postgres.render.com:5432/postgress_4sgg?schema=archive&ssl=true"]
    ports:
      - "8888:8000"

  explorer:
    image: subsquid/substrate-explorer:firesquid
    restart: on-failure
    environment:
      DB_TYPE: postgres
      DB_HOST: dpg-ct6bvabv2p9s739aq600-a.oregon-postgres.render.com
      DB_PORT: "5432"
      DB_NAME: postgress_4sgg
      DB_USER: postgress
      DB_PASS: YzHGemWnJKdIN53Lnxv6aPsW63TriqrG
      DB_SCHEMA: "archive"
    ports:
      - "4444:3000"
