version: "3.4"

services:
  ingest:
    image: subsquid/substrate-ingest:firesquid
    restart: on-failure
    command: >
      ["-e", "wss://kusama-rpc.polkadot.ioo",
       "--out", "postgres://postgress:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}]
    volumes:
      - ../:/app

  gateway:
    image: subsquid/substrate-gateway:firesquid
    restart: on-failure
    environment:
      DATABASE_MAX_CONNECTIONS: 5
      RUST_LOG: "actix_web=info,actix_server=info"
    command: >
      ["--database-url", "postgres://postgress:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}]
    ports:
      - "8888:8000"

  explorer:
    image: subsquid/substrate-explorer:firesquid
    restart: on-failure
    environment:
      DB_TYPE: postgres
      DB_HOST: ${DB_HOST}
      DB_PORT: "${DB_PORT}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASS: "${DB_PASS}"
      DB_SCHEMA: "archive"
    ports:
      - "4444:3000"
